server:
  port: 8206

spring:
  application:
    name: nacos-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

