server:
  port: 8207

spring:
  application:
    name: nacos-admin-webapp
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  main:
    allow-bean-definition-overriding: true

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头